version: '3'
services:
{{- if UseMySQL }}
  {{PkgName}}-mysql:
    container_name: {{PkgName}}-mysql
    image: mysql:latest
    ports:
      - 4306:3306
    volumes:
      - ./mountd/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
{{- end }}
{{- if UseMemcached }}
  {{PkgName}}-memcached:
    container_name: memcached
    image: memcached:1.5.2
    ports:
      - 21211:11211
{{- end }}
{{- if UseRedis }}
  {{PkgName}}-redis:
    container_name: {{PkgName}}-redis
    image: redis:4.0.2
    ports:
      - 7379:6379
    volumes:
      - ./mountd/redis/data:/data
{{- end }}
{{- if UseMongoDB }}
  {{PkgName}}-mongod:
    container_name: {{PkgName}}-mongod
    image: mongo:3.4.9
    volumes:
      - ./mountd/mongo/data/db:/data/db
    ports:
      - 37017:27017
{{- end }}